name: Build and test feature branch

on: 
    push:
        branches:
            - 'feature/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: "18.17.1"
                cache: yarn
            - name: Restore cache
              uses: actions/cache@v3
              with:
                path: |
                  .next/cache
                # Generate a new cache whenever packages or source files change.
                key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                # If source files changed but packages didn't, rebuild from a prior cache.
                restore-keys: |
                  ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
            - name: Install dependencies
              working-directory: ./my-awesome-website-next-app
              run: yarn install
            - name: Build with Next.js
              working-directory: ./my-awesome-website-next-app
              run: yarn build