name: GitHub Actions
on: [push]
env:
  AZURE_WEBAPP_NAME: my-resume-app
  AZURE_WEBAPP_PACKAGE_PATH: 'my-resume-react-app'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Upload artifact for deployment
        uses: actions/upload/artifact@v3
        with: 
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download artifact from build jobs
      uses: actions/download-artifact@v3
      with:
        name: my-resume

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
